export const STOCKS = [
  [
    'RELIANCE',
    'Reliance Industries',
    'NSE',
    'INR',
    'INDIAN_EQUITY',
    'Energy',
    'Conglomerate',
    1510.4,
  ],
  [
    'TCS',
    'Tata Consultancy Services',
    'NSE',
    'INR',
    'INDIAN_EQUITY',
    'Technology',
    'IT Services',
    3200,
  ],
  ['INFY', 'Infosys', 'NSE', 'INR', 'INDIAN_EQUITY', 'Technology', 'IT Services', 1550],
  ['HDFCBANK', 'HDFC Bank', 'NSE', 'INR', 'INDIAN_EQUITY', 'Financials', 'Banking', 1720],
  ['ICICIBANK', 'ICICI Bank', 'NSE', 'INR', 'INDIAN_EQUITY', 'Financials', 'Banking', 1280],
  ['ITC', 'ITC Limited', 'NSE', 'INR', 'INDIAN_EQUITY', 'Consumer Staples', 'Diversified', 425],
  ['SBIN', 'State Bank of India', 'NSE', 'INR', 'INDIAN_EQUITY', 'Financials', 'Banking', 820],
  ['LT', 'Larsen & Toubro', 'NSE', 'INR', 'INDIAN_EQUITY', 'Industrials', 'Engineering', 3550],
  ['AAPL', 'Apple', 'NASDAQ', 'USD', 'US_EQUITY', 'Technology', 'Consumer Electronics', 225],
  ['MSFT', 'Microsoft', 'NASDAQ', 'USD', 'US_EQUITY', 'Technology', 'Software', 440],
  ['GOOGL', 'Alphabet', 'NASDAQ', 'USD', 'US_EQUITY', 'Communication', 'Internet', 190],
  ['AMZN', 'Amazon', 'NASDAQ', 'USD', 'US_EQUITY', 'Consumer Discretionary', 'Retail', 210],
  ['NVDA', 'NVIDIA', 'NASDAQ', 'USD', 'US_EQUITY', 'Technology', 'Semiconductors', 145],
  ['META', 'Meta Platforms', 'NASDAQ', 'USD', 'US_EQUITY', 'Communication', 'Internet', 610],
  ['TSLA', 'Tesla', 'NASDAQ', 'USD', 'US_EQUITY', 'Consumer Discretionary', 'Automobiles', 320],
  ['NIFTYBEES', 'Nippon India Nifty 50 ETF', 'NSE', 'INR', 'ETF', 'Diversified', 'Index Fund', 275],
  ['QQQ', 'Invesco QQQ Trust', 'NASDAQ', 'USD', 'ETF', 'Diversified', 'Index Fund', 525],
  ['VOO', 'Vanguard S&P 500 ETF', 'NYSE', 'USD', 'ETF', 'Diversified', 'Index Fund', 555],
] as const;
export const BENCHMARKS = { NIFTY50: 25000, SENSEX: 82000, NASDAQ100: 22000, SP500: 6100 };
